### ISSUE TITLE
scade crashed while run in Mac mini M1 while launch 

### ISSUE THREAD

**Issue by ForeverCarousel** [scade-platform/ScadeExtensions#2]
Mac mini (M1, 2020) Apple M1
Xcode Version 13.2.1 (13C100)

**Comment by bulantsevajo** [comment]
Hi @ForeverCarousel thank you for the request and sorry for the late answer. We had an issue with M1 system, but we've fixed it in version 2.0.47 (February release). Please check that it works for you. 
If you will have any questions, we will try to help.
